name: "Run TODO to Issue"
on: ["push"]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"
              
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                  issue-number: 1
                  body: |
                    This is a multi-line test comment2
                    - With GitHub **Markdown** :sparkles:
                    - Created by [create-or-update-comment][1]
                  reactions: '+1'
