name: "Run TODO to Issue"
on: ["push"]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@v4"
              
            - name: "Workflow run manually, new issue created"
              if: ${{ github.event.pull_request.number == '' }}
              uses: JasonEtco/create-an-issue@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              id: create-issue                 
            
            - run: |
                echo "ISSUE_NUMBER=${{ steps.create-issue.outputs.number }}" >> $GITHUB_ENV
              if: ${{ github.event.pull_request.number == '' }}
            
            - run: |
                echo "ISSUE_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
              if: ${{ github.event.pull_request.number != '' }}
              
            - run: |
                echo Issue Number: ${{env.ISSUE_NUMBER}}
              
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                  issue-number: ${{env.ISSUE_NUMBER}}
                  body: |
                    This is a multi-line test comment3
                    - With GitHub **Markdown** :sparkles:
                    - Created by [create-or-update-comment][1]
                  reactions: '+1'
